//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace timviec.NguoiTimViec {
    
    
    public partial class ViecLamDaUngTuyen {
        
        /// <summary>
        /// lnkVLDaUngTuyen_TuHoSo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lnkVLDaUngTuyen_TuHoSo;
        
        /// <summary>
        /// lnkVLDaUngTuyen_TaiKhoan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lnkVLDaUngTuyen_TaiKhoan;
        
        /// <summary>
        /// lnkVLDaUngTuyen_ViecLamUngTuyen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lnkVLDaUngTuyen_ViecLamUngTuyen;
        
        /// <summary>
        /// lnkVLDaUngTuyen_NhaTuyenDungXemHoSo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lnkVLDaUngTuyen_NhaTuyenDungXemHoSo;
        
        /// <summary>
        /// grvNTDXemHS_DSNTD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView grvNTDXemHS_DSNTD;
    }
}
