<?xml version="1.0" encoding="utf-8"?><Database Name="WebsiteViecLam" Class="TimViecDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=KIENLE\KIENLE;Initial Catalog=WebsiteViecLam;User ID=sa" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="WebsiteViecLamConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CongTy" Member="CongTies">
    <Type Name="CongTy">
      <Column Name="ID_CongTy" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenCongTy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TenDangNhap" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="QuyMo" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NguoiDaiDien" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ID_ThanhPho" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CongTy_TinViecLam" Member="TinViecLams" ThisKey="ID_CongTy" OtherKey="ID_CongTy" Type="TinViecLam" />
      <Association Name="ThanhPho_CongTy" Member="ThanhPho" ThisKey="ID_ThanhPho" OtherKey="ID_ThanhPho" Type="ThanhPho" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VungMien" Member="VungMiens">
    <Type Name="VungMien">
      <Column Name="ID_Vung" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenVung" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="VungMien_TaiKhoan" Member="TaiKhoans" ThisKey="ID_Vung" OtherKey="ID_Vung" Type="TaiKhoan" />
      <Association Name="VungMien_ThanhPho" Member="ThanhPhos" ThisKey="ID_Vung" OtherKey="ID_Vung" Type="ThanhPho" />
    </Type>
  </Table>
  <Table Name="dbo.CV_UngVien" Member="CV_UngViens">
    <Type Name="CV_UngVien">
      <Column Name="ID_CV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_UngVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ID_NganhNghe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KyNang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ID_ViTri" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_TrinhDo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_KinhNghiem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgoaiNgu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MucLuong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BangCap" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="CV_UngVien_DangKy" Member="DangKies" ThisKey="ID_CV" OtherKey="ID_CV" Type="DangKy" />
      <Association Name="KinhNghiem_CV_UngVien" Member="KinhNghiem" ThisKey="ID_KinhNghiem" OtherKey="ID_KinhNghiem" Type="KinhNghiem" IsForeignKey="true" />
      <Association Name="NganhNghe_CV_UngVien" Member="NganhNghe" ThisKey="ID_NganhNghe" OtherKey="ID_NganhNghe" Type="NganhNghe" IsForeignKey="true" />
      <Association Name="TrinhDo_CV_UngVien" Member="TrinhDo" ThisKey="ID_TrinhDo" OtherKey="ID_TrinhDo" Type="TrinhDo" IsForeignKey="true" />
      <Association Name="UngVien_CV_UngVien" Member="UngVien" ThisKey="ID_UngVien" OtherKey="ID_UngVien" Type="UngVien" IsForeignKey="true" />
      <Association Name="ViTriUngTuyen_CV_UngVien" Member="ViTriUngTuyen" ThisKey="ID_ViTri" OtherKey="ID_ViTri" Type="ViTriUngTuyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DangKy" Member="DangKies">
    <Type Name="DangKy">
      <Column Name="ID_DangKy" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_CV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_ViecLam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayXem" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayUngTuyen" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="CV_UngVien_DangKy" Member="CV_UngVien" ThisKey="ID_CV" OtherKey="ID_CV" Type="CV_UngVien" IsForeignKey="true" />
      <Association Name="TinViecLam_DangKy" Member="TinViecLam" ThisKey="ID_ViecLam" OtherKey="ID_ViecLam" Type="TinViecLam" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KinhNghiem" Member="KinhNghiems">
    <Type Name="KinhNghiem">
      <Column Name="ID_KinhNghiem" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKinhNghiem" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="KinhNghiem_CV_UngVien" Member="CV_UngViens" ThisKey="ID_KinhNghiem" OtherKey="ID_KinhNghiem" Type="CV_UngVien" />
      <Association Name="KinhNghiem_TinViecLam" Member="TinViecLams" ThisKey="ID_KinhNghiem" OtherKey="ID_KinhNghiem" Type="TinViecLam" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiTaiKhoan" Member="LoaiTaiKhoans">
    <Type Name="LoaiTaiKhoan">
      <Column Name="ID_LoaiTaiKhoan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="LoaiTaiKhoan_TaiKhoan" Member="TaiKhoans" ThisKey="ID_LoaiTaiKhoan" OtherKey="ID_LoaiTaiKhoan" Type="TaiKhoan" />
    </Type>
  </Table>
  <Table Name="dbo.NganhNghe" Member="NganhNghes">
    <Type Name="NganhNghe">
      <Column Name="ID_NganhNghe" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNganhNghe" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="NganhNghe_CV_UngVien" Member="CV_UngViens" ThisKey="ID_NganhNghe" OtherKey="ID_NganhNghe" Type="CV_UngVien" />
      <Association Name="NganhNghe_TinViecLam" Member="TinViecLams" ThisKey="ID_NganhNghe" OtherKey="ID_NganhNghe" Type="TinViecLam" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="ID_TaiKhoan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_LoaiTaiKhoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenDangNhap" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ID_Vung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LoaiTaiKhoan_TaiKhoan" Member="LoaiTaiKhoan" ThisKey="ID_LoaiTaiKhoan" OtherKey="ID_LoaiTaiKhoan" Type="LoaiTaiKhoan" IsForeignKey="true" />
      <Association Name="VungMien_TaiKhoan" Member="VungMien" ThisKey="ID_Vung" OtherKey="ID_Vung" Type="VungMien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TinViecLam" Member="TinViecLams">
    <Type Name="TinViecLam">
      <Column Name="ID_ViecLam" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TieuDeViecLam" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ID_NganhNghe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_ViTri" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="YeuCauKyNang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ThoiGianThuViec" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ID_KinhNghiem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_TrinhDo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MucLuong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayDang" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ID_CongTy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="YeuCauHoSo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="TinViecLam_DangKy" Member="DangKies" ThisKey="ID_ViecLam" OtherKey="ID_ViecLam" Type="DangKy" />
      <Association Name="CongTy_TinViecLam" Member="CongTy" ThisKey="ID_CongTy" OtherKey="ID_CongTy" Type="CongTy" IsForeignKey="true" />
      <Association Name="KinhNghiem_TinViecLam" Member="KinhNghiem" ThisKey="ID_KinhNghiem" OtherKey="ID_KinhNghiem" Type="KinhNghiem" IsForeignKey="true" />
      <Association Name="NganhNghe_TinViecLam" Member="NganhNghe" ThisKey="ID_NganhNghe" OtherKey="ID_NganhNghe" Type="NganhNghe" IsForeignKey="true" />
      <Association Name="TrinhDo_TinViecLam" Member="TrinhDo" ThisKey="ID_TrinhDo" OtherKey="ID_TrinhDo" Type="TrinhDo" IsForeignKey="true" />
      <Association Name="ViTriUngTuyen_TinViecLam" Member="ViTriUngTuyen" ThisKey="ID_ViTri" OtherKey="ID_ViTri" Type="ViTriUngTuyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThanhPho" Member="ThanhPhos">
    <Type Name="ThanhPho">
      <Column Name="ID_ThanhPho" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenThanhPho" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ID_Vung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ThanhPho_CongTy" Member="CongTies" ThisKey="ID_ThanhPho" OtherKey="ID_ThanhPho" Type="CongTy" />
      <Association Name="ThanhPho_UngVien" Member="UngViens" ThisKey="ID_ThanhPho" OtherKey="ID_ThanhPho" Type="UngVien" />
      <Association Name="VungMien_ThanhPho" Member="VungMien" ThisKey="ID_Vung" OtherKey="ID_Vung" Type="VungMien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrinhDo" Member="TrinhDos">
    <Type Name="TrinhDo">
      <Column Name="ID_TrinhDo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTrinhDo" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="TrinhDo_CV_UngVien" Member="CV_UngViens" ThisKey="ID_TrinhDo" OtherKey="ID_TrinhDo" Type="CV_UngVien" />
      <Association Name="TrinhDo_TinViecLam" Member="TinViecLams" ThisKey="ID_TrinhDo" OtherKey="ID_TrinhDo" Type="TinViecLam" />
    </Type>
  </Table>
  <Table Name="dbo.UngVien" Member="UngViens">
    <Type Name="UngVien">
      <Column Name="ID_UngVien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ID_ThanhPho" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="UngVien_CV_UngVien" Member="CV_UngViens" ThisKey="ID_UngVien" OtherKey="ID_UngVien" Type="CV_UngVien" />
      <Association Name="ThanhPho_UngVien" Member="ThanhPho" ThisKey="ID_ThanhPho" OtherKey="ID_ThanhPho" Type="ThanhPho" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViTriUngTuyen" Member="ViTriUngTuyens">
    <Type Name="ViTriUngTuyen">
      <Column Name="ID_ViTri" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenViTri" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="ViTriUngTuyen_CV_UngVien" Member="CV_UngViens" ThisKey="ID_ViTri" OtherKey="ID_ViTri" Type="CV_UngVien" />
      <Association Name="ViTriUngTuyen_TinViecLam" Member="TinViecLams" ThisKey="ID_ViTri" OtherKey="ID_ViTri" Type="TinViecLam" />
    </Type>
  </Table>
</Database>