#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WebsiteViecLam")]
	public partial class TimViecDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCongTy(CongTy instance);
    partial void UpdateCongTy(CongTy instance);
    partial void DeleteCongTy(CongTy instance);
    partial void InsertVungMien(VungMien instance);
    partial void UpdateVungMien(VungMien instance);
    partial void DeleteVungMien(VungMien instance);
    partial void InsertCV_UngVien(CV_UngVien instance);
    partial void UpdateCV_UngVien(CV_UngVien instance);
    partial void DeleteCV_UngVien(CV_UngVien instance);
    partial void InsertDangKy(DangKy instance);
    partial void UpdateDangKy(DangKy instance);
    partial void DeleteDangKy(DangKy instance);
    partial void InsertKinhNghiem(KinhNghiem instance);
    partial void UpdateKinhNghiem(KinhNghiem instance);
    partial void DeleteKinhNghiem(KinhNghiem instance);
    partial void InsertLoaiTaiKhoan(LoaiTaiKhoan instance);
    partial void UpdateLoaiTaiKhoan(LoaiTaiKhoan instance);
    partial void DeleteLoaiTaiKhoan(LoaiTaiKhoan instance);
    partial void InsertNganhNghe(NganhNghe instance);
    partial void UpdateNganhNghe(NganhNghe instance);
    partial void DeleteNganhNghe(NganhNghe instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertTinViecLam(TinViecLam instance);
    partial void UpdateTinViecLam(TinViecLam instance);
    partial void DeleteTinViecLam(TinViecLam instance);
    partial void InsertThanhPho(ThanhPho instance);
    partial void UpdateThanhPho(ThanhPho instance);
    partial void DeleteThanhPho(ThanhPho instance);
    partial void InsertTrinhDo(TrinhDo instance);
    partial void UpdateTrinhDo(TrinhDo instance);
    partial void DeleteTrinhDo(TrinhDo instance);
    partial void InsertUngVien(UngVien instance);
    partial void UpdateUngVien(UngVien instance);
    partial void DeleteUngVien(UngVien instance);
    partial void InsertViTriUngTuyen(ViTriUngTuyen instance);
    partial void UpdateViTriUngTuyen(ViTriUngTuyen instance);
    partial void DeleteViTriUngTuyen(ViTriUngTuyen instance);
    #endregion
		
		public TimViecDBDataContext() : 
				base(global::DAL.Properties.Settings.Default.WebsiteViecLamConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TimViecDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TimViecDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TimViecDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TimViecDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CongTy> CongTies
		{
			get
			{
				return this.GetTable<CongTy>();
			}
		}
		
		public System.Data.Linq.Table<VungMien> VungMiens
		{
			get
			{
				return this.GetTable<VungMien>();
			}
		}
		
		public System.Data.Linq.Table<CV_UngVien> CV_UngViens
		{
			get
			{
				return this.GetTable<CV_UngVien>();
			}
		}
		
		public System.Data.Linq.Table<DangKy> DangKies
		{
			get
			{
				return this.GetTable<DangKy>();
			}
		}
		
		public System.Data.Linq.Table<KinhNghiem> KinhNghiems
		{
			get
			{
				return this.GetTable<KinhNghiem>();
			}
		}
		
		public System.Data.Linq.Table<LoaiTaiKhoan> LoaiTaiKhoans
		{
			get
			{
				return this.GetTable<LoaiTaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<NganhNghe> NganhNghes
		{
			get
			{
				return this.GetTable<NganhNghe>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<TinViecLam> TinViecLams
		{
			get
			{
				return this.GetTable<TinViecLam>();
			}
		}
		
		public System.Data.Linq.Table<ThanhPho> ThanhPhos
		{
			get
			{
				return this.GetTable<ThanhPho>();
			}
		}
		
		public System.Data.Linq.Table<TrinhDo> TrinhDos
		{
			get
			{
				return this.GetTable<TrinhDo>();
			}
		}
		
		public System.Data.Linq.Table<UngVien> UngViens
		{
			get
			{
				return this.GetTable<UngVien>();
			}
		}
		
		public System.Data.Linq.Table<ViTriUngTuyen> ViTriUngTuyens
		{
			get
			{
				return this.GetTable<ViTriUngTuyen>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CongTy")]
	public partial class CongTy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CongTy;
		
		private string _TenCongTy;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _DiaChi;
		
		private string _QuyMo;
		
		private string _SDT;
		
		private string _Website;
		
		private string _MoTa;
		
		private string _NguoiDaiDien;
		
		private string _Email;
		
		private System.Nullable<int> _ID_ThanhPho;
		
		private EntitySet<TinViecLam> _TinViecLams;
		
		private EntityRef<ThanhPho> _ThanhPho;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CongTyChanging(int value);
    partial void OnID_CongTyChanged();
    partial void OnTenCongTyChanging(string value);
    partial void OnTenCongTyChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnQuyMoChanging(string value);
    partial void OnQuyMoChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnWebsiteChanging(string value);
    partial void OnWebsiteChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnNguoiDaiDienChanging(string value);
    partial void OnNguoiDaiDienChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnID_ThanhPhoChanging(System.Nullable<int> value);
    partial void OnID_ThanhPhoChanged();
    #endregion
		
		public CongTy()
		{
			this._TinViecLams = new EntitySet<TinViecLam>(new Action<TinViecLam>(this.attach_TinViecLams), new Action<TinViecLam>(this.detach_TinViecLams));
			this._ThanhPho = default(EntityRef<ThanhPho>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CongTy", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CongTy
		{
			get
			{
				return this._ID_CongTy;
			}
			set
			{
				if ((this._ID_CongTy != value))
				{
					this.OnID_CongTyChanging(value);
					this.SendPropertyChanging();
					this._ID_CongTy = value;
					this.SendPropertyChanged("ID_CongTy");
					this.OnID_CongTyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCongTy", DbType="NVarChar(255)")]
		public string TenCongTy
		{
			get
			{
				return this._TenCongTy;
			}
			set
			{
				if ((this._TenCongTy != value))
				{
					this.OnTenCongTyChanging(value);
					this.SendPropertyChanging();
					this._TenCongTy = value;
					this.SendPropertyChanged("TenCongTy");
					this.OnTenCongTyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(150)")]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(250)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyMo", DbType="NVarChar(250)")]
		public string QuyMo
		{
			get
			{
				return this._QuyMo;
			}
			set
			{
				if ((this._QuyMo != value))
				{
					this.OnQuyMoChanging(value);
					this.SendPropertyChanging();
					this._QuyMo = value;
					this.SendPropertyChanged("QuyMo");
					this.OnQuyMoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(50)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="VarChar(50)")]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this.OnWebsiteChanging(value);
					this.SendPropertyChanging();
					this._Website = value;
					this.SendPropertyChanged("Website");
					this.OnWebsiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiDaiDien", DbType="NVarChar(150)")]
		public string NguoiDaiDien
		{
			get
			{
				return this._NguoiDaiDien;
			}
			set
			{
				if ((this._NguoiDaiDien != value))
				{
					this.OnNguoiDaiDienChanging(value);
					this.SendPropertyChanging();
					this._NguoiDaiDien = value;
					this.SendPropertyChanged("NguoiDaiDien");
					this.OnNguoiDaiDienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ThanhPho", DbType="Int")]
		public System.Nullable<int> ID_ThanhPho
		{
			get
			{
				return this._ID_ThanhPho;
			}
			set
			{
				if ((this._ID_ThanhPho != value))
				{
					if (this._ThanhPho.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ThanhPhoChanging(value);
					this.SendPropertyChanging();
					this._ID_ThanhPho = value;
					this.SendPropertyChanged("ID_ThanhPho");
					this.OnID_ThanhPhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongTy_TinViecLam", Storage="_TinViecLams", ThisKey="ID_CongTy", OtherKey="ID_CongTy")]
		public EntitySet<TinViecLam> TinViecLams
		{
			get
			{
				return this._TinViecLams;
			}
			set
			{
				this._TinViecLams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhPho_CongTy", Storage="_ThanhPho", ThisKey="ID_ThanhPho", OtherKey="ID_ThanhPho", IsForeignKey=true)]
		public ThanhPho ThanhPho
		{
			get
			{
				return this._ThanhPho.Entity;
			}
			set
			{
				ThanhPho previousValue = this._ThanhPho.Entity;
				if (((previousValue != value) 
							|| (this._ThanhPho.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThanhPho.Entity = null;
						previousValue.CongTies.Remove(this);
					}
					this._ThanhPho.Entity = value;
					if ((value != null))
					{
						value.CongTies.Add(this);
						this._ID_ThanhPho = value.ID_ThanhPho;
					}
					else
					{
						this._ID_ThanhPho = default(Nullable<int>);
					}
					this.SendPropertyChanged("ThanhPho");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TinViecLams(TinViecLam entity)
		{
			this.SendPropertyChanging();
			entity.CongTy = this;
		}
		
		private void detach_TinViecLams(TinViecLam entity)
		{
			this.SendPropertyChanging();
			entity.CongTy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VungMien")]
	public partial class VungMien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Vung;
		
		private string _TenVung;
		
		private EntitySet<TaiKhoan> _TaiKhoans;
		
		private EntitySet<ThanhPho> _ThanhPhos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_VungChanging(int value);
    partial void OnID_VungChanged();
    partial void OnTenVungChanging(string value);
    partial void OnTenVungChanged();
    #endregion
		
		public VungMien()
		{
			this._TaiKhoans = new EntitySet<TaiKhoan>(new Action<TaiKhoan>(this.attach_TaiKhoans), new Action<TaiKhoan>(this.detach_TaiKhoans));
			this._ThanhPhos = new EntitySet<ThanhPho>(new Action<ThanhPho>(this.attach_ThanhPhos), new Action<ThanhPho>(this.detach_ThanhPhos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Vung", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Vung
		{
			get
			{
				return this._ID_Vung;
			}
			set
			{
				if ((this._ID_Vung != value))
				{
					this.OnID_VungChanging(value);
					this.SendPropertyChanging();
					this._ID_Vung = value;
					this.SendPropertyChanged("ID_Vung");
					this.OnID_VungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVung", DbType="NVarChar(150)")]
		public string TenVung
		{
			get
			{
				return this._TenVung;
			}
			set
			{
				if ((this._TenVung != value))
				{
					this.OnTenVungChanging(value);
					this.SendPropertyChanging();
					this._TenVung = value;
					this.SendPropertyChanged("TenVung");
					this.OnTenVungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VungMien_TaiKhoan", Storage="_TaiKhoans", ThisKey="ID_Vung", OtherKey="ID_Vung")]
		public EntitySet<TaiKhoan> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VungMien_ThanhPho", Storage="_ThanhPhos", ThisKey="ID_Vung", OtherKey="ID_Vung")]
		public EntitySet<ThanhPho> ThanhPhos
		{
			get
			{
				return this._ThanhPhos;
			}
			set
			{
				this._ThanhPhos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.VungMien = this;
		}
		
		private void detach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.VungMien = null;
		}
		
		private void attach_ThanhPhos(ThanhPho entity)
		{
			this.SendPropertyChanging();
			entity.VungMien = this;
		}
		
		private void detach_ThanhPhos(ThanhPho entity)
		{
			this.SendPropertyChanging();
			entity.VungMien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CV_UngVien")]
	public partial class CV_UngVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CV;
		
		private System.Nullable<int> _ID_UngVien;
		
		private string _TieuDe;
		
		private System.Nullable<int> _ID_NganhNghe;
		
		private string _KyNang;
		
		private System.Nullable<int> _ID_ViTri;
		
		private System.Nullable<int> _ID_TrinhDo;
		
		private System.Nullable<int> _ID_KinhNghiem;
		
		private string _NgoaiNgu;
		
		private string _MucLuong;
		
		private string _BangCap;
		
		private System.Nullable<bool> _TrangThai;
		
		private EntitySet<DangKy> _DangKies;
		
		private EntityRef<KinhNghiem> _KinhNghiem;
		
		private EntityRef<NganhNghe> _NganhNghe;
		
		private EntityRef<TrinhDo> _TrinhDo;
		
		private EntityRef<UngVien> _UngVien;
		
		private EntityRef<ViTriUngTuyen> _ViTriUngTuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CVChanging(int value);
    partial void OnID_CVChanged();
    partial void OnID_UngVienChanging(System.Nullable<int> value);
    partial void OnID_UngVienChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnID_NganhNgheChanging(System.Nullable<int> value);
    partial void OnID_NganhNgheChanged();
    partial void OnKyNangChanging(string value);
    partial void OnKyNangChanged();
    partial void OnID_ViTriChanging(System.Nullable<int> value);
    partial void OnID_ViTriChanged();
    partial void OnID_TrinhDoChanging(System.Nullable<int> value);
    partial void OnID_TrinhDoChanged();
    partial void OnID_KinhNghiemChanging(System.Nullable<int> value);
    partial void OnID_KinhNghiemChanged();
    partial void OnNgoaiNguChanging(string value);
    partial void OnNgoaiNguChanged();
    partial void OnMucLuongChanging(string value);
    partial void OnMucLuongChanged();
    partial void OnBangCapChanging(string value);
    partial void OnBangCapChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public CV_UngVien()
		{
			this._DangKies = new EntitySet<DangKy>(new Action<DangKy>(this.attach_DangKies), new Action<DangKy>(this.detach_DangKies));
			this._KinhNghiem = default(EntityRef<KinhNghiem>);
			this._NganhNghe = default(EntityRef<NganhNghe>);
			this._TrinhDo = default(EntityRef<TrinhDo>);
			this._UngVien = default(EntityRef<UngVien>);
			this._ViTriUngTuyen = default(EntityRef<ViTriUngTuyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CV
		{
			get
			{
				return this._ID_CV;
			}
			set
			{
				if ((this._ID_CV != value))
				{
					this.OnID_CVChanging(value);
					this.SendPropertyChanging();
					this._ID_CV = value;
					this.SendPropertyChanged("ID_CV");
					this.OnID_CVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_UngVien", DbType="Int")]
		public System.Nullable<int> ID_UngVien
		{
			get
			{
				return this._ID_UngVien;
			}
			set
			{
				if ((this._ID_UngVien != value))
				{
					if (this._UngVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_UngVienChanging(value);
					this.SendPropertyChanging();
					this._ID_UngVien = value;
					this.SendPropertyChanged("ID_UngVien");
					this.OnID_UngVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(255)")]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NganhNghe", DbType="Int")]
		public System.Nullable<int> ID_NganhNghe
		{
			get
			{
				return this._ID_NganhNghe;
			}
			set
			{
				if ((this._ID_NganhNghe != value))
				{
					if (this._NganhNghe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_NganhNgheChanging(value);
					this.SendPropertyChanging();
					this._ID_NganhNghe = value;
					this.SendPropertyChanged("ID_NganhNghe");
					this.OnID_NganhNgheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KyNang", DbType="NVarChar(MAX)")]
		public string KyNang
		{
			get
			{
				return this._KyNang;
			}
			set
			{
				if ((this._KyNang != value))
				{
					this.OnKyNangChanging(value);
					this.SendPropertyChanging();
					this._KyNang = value;
					this.SendPropertyChanged("KyNang");
					this.OnKyNangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ViTri", DbType="Int")]
		public System.Nullable<int> ID_ViTri
		{
			get
			{
				return this._ID_ViTri;
			}
			set
			{
				if ((this._ID_ViTri != value))
				{
					if (this._ViTriUngTuyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ViTriChanging(value);
					this.SendPropertyChanging();
					this._ID_ViTri = value;
					this.SendPropertyChanged("ID_ViTri");
					this.OnID_ViTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TrinhDo", DbType="Int")]
		public System.Nullable<int> ID_TrinhDo
		{
			get
			{
				return this._ID_TrinhDo;
			}
			set
			{
				if ((this._ID_TrinhDo != value))
				{
					if (this._TrinhDo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_TrinhDoChanging(value);
					this.SendPropertyChanging();
					this._ID_TrinhDo = value;
					this.SendPropertyChanged("ID_TrinhDo");
					this.OnID_TrinhDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_KinhNghiem", DbType="Int")]
		public System.Nullable<int> ID_KinhNghiem
		{
			get
			{
				return this._ID_KinhNghiem;
			}
			set
			{
				if ((this._ID_KinhNghiem != value))
				{
					if (this._KinhNghiem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_KinhNghiemChanging(value);
					this.SendPropertyChanging();
					this._ID_KinhNghiem = value;
					this.SendPropertyChanged("ID_KinhNghiem");
					this.OnID_KinhNghiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgoaiNgu", DbType="NVarChar(255)")]
		public string NgoaiNgu
		{
			get
			{
				return this._NgoaiNgu;
			}
			set
			{
				if ((this._NgoaiNgu != value))
				{
					this.OnNgoaiNguChanging(value);
					this.SendPropertyChanging();
					this._NgoaiNgu = value;
					this.SendPropertyChanged("NgoaiNgu");
					this.OnNgoaiNguChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucLuong", DbType="NVarChar(100)")]
		public string MucLuong
		{
			get
			{
				return this._MucLuong;
			}
			set
			{
				if ((this._MucLuong != value))
				{
					this.OnMucLuongChanging(value);
					this.SendPropertyChanging();
					this._MucLuong = value;
					this.SendPropertyChanged("MucLuong");
					this.OnMucLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BangCap", DbType="NVarChar(200)")]
		public string BangCap
		{
			get
			{
				return this._BangCap;
			}
			set
			{
				if ((this._BangCap != value))
				{
					this.OnBangCapChanging(value);
					this.SendPropertyChanging();
					this._BangCap = value;
					this.SendPropertyChanged("BangCap");
					this.OnBangCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CV_UngVien_DangKy", Storage="_DangKies", ThisKey="ID_CV", OtherKey="ID_CV")]
		public EntitySet<DangKy> DangKies
		{
			get
			{
				return this._DangKies;
			}
			set
			{
				this._DangKies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KinhNghiem_CV_UngVien", Storage="_KinhNghiem", ThisKey="ID_KinhNghiem", OtherKey="ID_KinhNghiem", IsForeignKey=true)]
		public KinhNghiem KinhNghiem
		{
			get
			{
				return this._KinhNghiem.Entity;
			}
			set
			{
				KinhNghiem previousValue = this._KinhNghiem.Entity;
				if (((previousValue != value) 
							|| (this._KinhNghiem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KinhNghiem.Entity = null;
						previousValue.CV_UngViens.Remove(this);
					}
					this._KinhNghiem.Entity = value;
					if ((value != null))
					{
						value.CV_UngViens.Add(this);
						this._ID_KinhNghiem = value.ID_KinhNghiem;
					}
					else
					{
						this._ID_KinhNghiem = default(Nullable<int>);
					}
					this.SendPropertyChanged("KinhNghiem");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NganhNghe_CV_UngVien", Storage="_NganhNghe", ThisKey="ID_NganhNghe", OtherKey="ID_NganhNghe", IsForeignKey=true)]
		public NganhNghe NganhNghe
		{
			get
			{
				return this._NganhNghe.Entity;
			}
			set
			{
				NganhNghe previousValue = this._NganhNghe.Entity;
				if (((previousValue != value) 
							|| (this._NganhNghe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NganhNghe.Entity = null;
						previousValue.CV_UngViens.Remove(this);
					}
					this._NganhNghe.Entity = value;
					if ((value != null))
					{
						value.CV_UngViens.Add(this);
						this._ID_NganhNghe = value.ID_NganhNghe;
					}
					else
					{
						this._ID_NganhNghe = default(Nullable<int>);
					}
					this.SendPropertyChanged("NganhNghe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrinhDo_CV_UngVien", Storage="_TrinhDo", ThisKey="ID_TrinhDo", OtherKey="ID_TrinhDo", IsForeignKey=true)]
		public TrinhDo TrinhDo
		{
			get
			{
				return this._TrinhDo.Entity;
			}
			set
			{
				TrinhDo previousValue = this._TrinhDo.Entity;
				if (((previousValue != value) 
							|| (this._TrinhDo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TrinhDo.Entity = null;
						previousValue.CV_UngViens.Remove(this);
					}
					this._TrinhDo.Entity = value;
					if ((value != null))
					{
						value.CV_UngViens.Add(this);
						this._ID_TrinhDo = value.ID_TrinhDo;
					}
					else
					{
						this._ID_TrinhDo = default(Nullable<int>);
					}
					this.SendPropertyChanged("TrinhDo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UngVien_CV_UngVien", Storage="_UngVien", ThisKey="ID_UngVien", OtherKey="ID_UngVien", IsForeignKey=true)]
		public UngVien UngVien
		{
			get
			{
				return this._UngVien.Entity;
			}
			set
			{
				UngVien previousValue = this._UngVien.Entity;
				if (((previousValue != value) 
							|| (this._UngVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UngVien.Entity = null;
						previousValue.CV_UngViens.Remove(this);
					}
					this._UngVien.Entity = value;
					if ((value != null))
					{
						value.CV_UngViens.Add(this);
						this._ID_UngVien = value.ID_UngVien;
					}
					else
					{
						this._ID_UngVien = default(Nullable<int>);
					}
					this.SendPropertyChanged("UngVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ViTriUngTuyen_CV_UngVien", Storage="_ViTriUngTuyen", ThisKey="ID_ViTri", OtherKey="ID_ViTri", IsForeignKey=true)]
		public ViTriUngTuyen ViTriUngTuyen
		{
			get
			{
				return this._ViTriUngTuyen.Entity;
			}
			set
			{
				ViTriUngTuyen previousValue = this._ViTriUngTuyen.Entity;
				if (((previousValue != value) 
							|| (this._ViTriUngTuyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ViTriUngTuyen.Entity = null;
						previousValue.CV_UngViens.Remove(this);
					}
					this._ViTriUngTuyen.Entity = value;
					if ((value != null))
					{
						value.CV_UngViens.Add(this);
						this._ID_ViTri = value.ID_ViTri;
					}
					else
					{
						this._ID_ViTri = default(Nullable<int>);
					}
					this.SendPropertyChanged("ViTriUngTuyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DangKies(DangKy entity)
		{
			this.SendPropertyChanging();
			entity.CV_UngVien = this;
		}
		
		private void detach_DangKies(DangKy entity)
		{
			this.SendPropertyChanging();
			entity.CV_UngVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangKy")]
	public partial class DangKy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_DangKy;
		
		private System.Nullable<int> _ID_CV;
		
		private System.Nullable<int> _ID_ViecLam;
		
		private System.Nullable<System.DateTime> _NgayXem;
		
		private System.Nullable<System.DateTime> _NgayUngTuyen;
		
		private System.Nullable<bool> _TrangThai;
		
		private EntityRef<CV_UngVien> _CV_UngVien;
		
		private EntityRef<TinViecLam> _TinViecLam;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DangKyChanging(int value);
    partial void OnID_DangKyChanged();
    partial void OnID_CVChanging(System.Nullable<int> value);
    partial void OnID_CVChanged();
    partial void OnID_ViecLamChanging(System.Nullable<int> value);
    partial void OnID_ViecLamChanged();
    partial void OnNgayXemChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayXemChanged();
    partial void OnNgayUngTuyenChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayUngTuyenChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public DangKy()
		{
			this._CV_UngVien = default(EntityRef<CV_UngVien>);
			this._TinViecLam = default(EntityRef<TinViecLam>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DangKy", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_DangKy
		{
			get
			{
				return this._ID_DangKy;
			}
			set
			{
				if ((this._ID_DangKy != value))
				{
					this.OnID_DangKyChanging(value);
					this.SendPropertyChanging();
					this._ID_DangKy = value;
					this.SendPropertyChanged("ID_DangKy");
					this.OnID_DangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CV", DbType="Int")]
		public System.Nullable<int> ID_CV
		{
			get
			{
				return this._ID_CV;
			}
			set
			{
				if ((this._ID_CV != value))
				{
					if (this._CV_UngVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_CVChanging(value);
					this.SendPropertyChanging();
					this._ID_CV = value;
					this.SendPropertyChanged("ID_CV");
					this.OnID_CVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ViecLam", DbType="Int")]
		public System.Nullable<int> ID_ViecLam
		{
			get
			{
				return this._ID_ViecLam;
			}
			set
			{
				if ((this._ID_ViecLam != value))
				{
					if (this._TinViecLam.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ViecLamChanging(value);
					this.SendPropertyChanging();
					this._ID_ViecLam = value;
					this.SendPropertyChanged("ID_ViecLam");
					this.OnID_ViecLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayXem", DbType="Date")]
		public System.Nullable<System.DateTime> NgayXem
		{
			get
			{
				return this._NgayXem;
			}
			set
			{
				if ((this._NgayXem != value))
				{
					this.OnNgayXemChanging(value);
					this.SendPropertyChanging();
					this._NgayXem = value;
					this.SendPropertyChanged("NgayXem");
					this.OnNgayXemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayUngTuyen", DbType="Date")]
		public System.Nullable<System.DateTime> NgayUngTuyen
		{
			get
			{
				return this._NgayUngTuyen;
			}
			set
			{
				if ((this._NgayUngTuyen != value))
				{
					this.OnNgayUngTuyenChanging(value);
					this.SendPropertyChanging();
					this._NgayUngTuyen = value;
					this.SendPropertyChanged("NgayUngTuyen");
					this.OnNgayUngTuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CV_UngVien_DangKy", Storage="_CV_UngVien", ThisKey="ID_CV", OtherKey="ID_CV", IsForeignKey=true)]
		public CV_UngVien CV_UngVien
		{
			get
			{
				return this._CV_UngVien.Entity;
			}
			set
			{
				CV_UngVien previousValue = this._CV_UngVien.Entity;
				if (((previousValue != value) 
							|| (this._CV_UngVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CV_UngVien.Entity = null;
						previousValue.DangKies.Remove(this);
					}
					this._CV_UngVien.Entity = value;
					if ((value != null))
					{
						value.DangKies.Add(this);
						this._ID_CV = value.ID_CV;
					}
					else
					{
						this._ID_CV = default(Nullable<int>);
					}
					this.SendPropertyChanged("CV_UngVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TinViecLam_DangKy", Storage="_TinViecLam", ThisKey="ID_ViecLam", OtherKey="ID_ViecLam", IsForeignKey=true)]
		public TinViecLam TinViecLam
		{
			get
			{
				return this._TinViecLam.Entity;
			}
			set
			{
				TinViecLam previousValue = this._TinViecLam.Entity;
				if (((previousValue != value) 
							|| (this._TinViecLam.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TinViecLam.Entity = null;
						previousValue.DangKies.Remove(this);
					}
					this._TinViecLam.Entity = value;
					if ((value != null))
					{
						value.DangKies.Add(this);
						this._ID_ViecLam = value.ID_ViecLam;
					}
					else
					{
						this._ID_ViecLam = default(Nullable<int>);
					}
					this.SendPropertyChanged("TinViecLam");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KinhNghiem")]
	public partial class KinhNghiem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_KinhNghiem;
		
		private string _TenKinhNghiem;
		
		private EntitySet<CV_UngVien> _CV_UngViens;
		
		private EntitySet<TinViecLam> _TinViecLams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_KinhNghiemChanging(int value);
    partial void OnID_KinhNghiemChanged();
    partial void OnTenKinhNghiemChanging(string value);
    partial void OnTenKinhNghiemChanged();
    #endregion
		
		public KinhNghiem()
		{
			this._CV_UngViens = new EntitySet<CV_UngVien>(new Action<CV_UngVien>(this.attach_CV_UngViens), new Action<CV_UngVien>(this.detach_CV_UngViens));
			this._TinViecLams = new EntitySet<TinViecLam>(new Action<TinViecLam>(this.attach_TinViecLams), new Action<TinViecLam>(this.detach_TinViecLams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_KinhNghiem", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_KinhNghiem
		{
			get
			{
				return this._ID_KinhNghiem;
			}
			set
			{
				if ((this._ID_KinhNghiem != value))
				{
					this.OnID_KinhNghiemChanging(value);
					this.SendPropertyChanging();
					this._ID_KinhNghiem = value;
					this.SendPropertyChanged("ID_KinhNghiem");
					this.OnID_KinhNghiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKinhNghiem", DbType="NVarChar(255)")]
		public string TenKinhNghiem
		{
			get
			{
				return this._TenKinhNghiem;
			}
			set
			{
				if ((this._TenKinhNghiem != value))
				{
					this.OnTenKinhNghiemChanging(value);
					this.SendPropertyChanging();
					this._TenKinhNghiem = value;
					this.SendPropertyChanged("TenKinhNghiem");
					this.OnTenKinhNghiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KinhNghiem_CV_UngVien", Storage="_CV_UngViens", ThisKey="ID_KinhNghiem", OtherKey="ID_KinhNghiem")]
		public EntitySet<CV_UngVien> CV_UngViens
		{
			get
			{
				return this._CV_UngViens;
			}
			set
			{
				this._CV_UngViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KinhNghiem_TinViecLam", Storage="_TinViecLams", ThisKey="ID_KinhNghiem", OtherKey="ID_KinhNghiem")]
		public EntitySet<TinViecLam> TinViecLams
		{
			get
			{
				return this._TinViecLams;
			}
			set
			{
				this._TinViecLams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CV_UngViens(CV_UngVien entity)
		{
			this.SendPropertyChanging();
			entity.KinhNghiem = this;
		}
		
		private void detach_CV_UngViens(CV_UngVien entity)
		{
			this.SendPropertyChanging();
			entity.KinhNghiem = null;
		}
		
		private void attach_TinViecLams(TinViecLam entity)
		{
			this.SendPropertyChanging();
			entity.KinhNghiem = this;
		}
		
		private void detach_TinViecLams(TinViecLam entity)
		{
			this.SendPropertyChanging();
			entity.KinhNghiem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiTaiKhoan")]
	public partial class LoaiTaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_LoaiTaiKhoan;
		
		private string _TenLoai;
		
		private EntitySet<TaiKhoan> _TaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_LoaiTaiKhoanChanging(int value);
    partial void OnID_LoaiTaiKhoanChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    #endregion
		
		public LoaiTaiKhoan()
		{
			this._TaiKhoans = new EntitySet<TaiKhoan>(new Action<TaiKhoan>(this.attach_TaiKhoans), new Action<TaiKhoan>(this.detach_TaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LoaiTaiKhoan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_LoaiTaiKhoan
		{
			get
			{
				return this._ID_LoaiTaiKhoan;
			}
			set
			{
				if ((this._ID_LoaiTaiKhoan != value))
				{
					this.OnID_LoaiTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._ID_LoaiTaiKhoan = value;
					this.SendPropertyChanged("ID_LoaiTaiKhoan");
					this.OnID_LoaiTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(255)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiTaiKhoan_TaiKhoan", Storage="_TaiKhoans", ThisKey="ID_LoaiTaiKhoan", OtherKey="ID_LoaiTaiKhoan")]
		public EntitySet<TaiKhoan> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.LoaiTaiKhoan = this;
		}
		
		private void detach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.LoaiTaiKhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NganhNghe")]
	public partial class NganhNghe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_NganhNghe;
		
		private string _TenNganhNghe;
		
		private EntitySet<CV_UngVien> _CV_UngViens;
		
		private EntitySet<TinViecLam> _TinViecLams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_NganhNgheChanging(int value);
    partial void OnID_NganhNgheChanged();
    partial void OnTenNganhNgheChanging(string value);
    partial void OnTenNganhNgheChanged();
    #endregion
		
		public NganhNghe()
		{
			this._CV_UngViens = new EntitySet<CV_UngVien>(new Action<CV_UngVien>(this.attach_CV_UngViens), new Action<CV_UngVien>(this.detach_CV_UngViens));
			this._TinViecLams = new EntitySet<TinViecLam>(new Action<TinViecLam>(this.attach_TinViecLams), new Action<TinViecLam>(this.detach_TinViecLams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NganhNghe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_NganhNghe
		{
			get
			{
				return this._ID_NganhNghe;
			}
			set
			{
				if ((this._ID_NganhNghe != value))
				{
					this.OnID_NganhNgheChanging(value);
					this.SendPropertyChanging();
					this._ID_NganhNghe = value;
					this.SendPropertyChanged("ID_NganhNghe");
					this.OnID_NganhNgheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNganhNghe", DbType="NVarChar(250)")]
		public string TenNganhNghe
		{
			get
			{
				return this._TenNganhNghe;
			}
			set
			{
				if ((this._TenNganhNghe != value))
				{
					this.OnTenNganhNgheChanging(value);
					this.SendPropertyChanging();
					this._TenNganhNghe = value;
					this.SendPropertyChanged("TenNganhNghe");
					this.OnTenNganhNgheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NganhNghe_CV_UngVien", Storage="_CV_UngViens", ThisKey="ID_NganhNghe", OtherKey="ID_NganhNghe")]
		public EntitySet<CV_UngVien> CV_UngViens
		{
			get
			{
				return this._CV_UngViens;
			}
			set
			{
				this._CV_UngViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NganhNghe_TinViecLam", Storage="_TinViecLams", ThisKey="ID_NganhNghe", OtherKey="ID_NganhNghe")]
		public EntitySet<TinViecLam> TinViecLams
		{
			get
			{
				return this._TinViecLams;
			}
			set
			{
				this._TinViecLams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CV_UngViens(CV_UngVien entity)
		{
			this.SendPropertyChanging();
			entity.NganhNghe = this;
		}
		
		private void detach_CV_UngViens(CV_UngVien entity)
		{
			this.SendPropertyChanging();
			entity.NganhNghe = null;
		}
		
		private void attach_TinViecLams(TinViecLam entity)
		{
			this.SendPropertyChanging();
			entity.NganhNghe = this;
		}
		
		private void detach_TinViecLams(TinViecLam entity)
		{
			this.SendPropertyChanging();
			entity.NganhNghe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_TaiKhoan;
		
		private System.Nullable<int> _ID_LoaiTaiKhoan;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _HoTen;
		
		private string _Email;
		
		private string _SDT;
		
		private System.Nullable<int> _ID_Vung;
		
		private EntityRef<LoaiTaiKhoan> _LoaiTaiKhoan;
		
		private EntityRef<VungMien> _VungMien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_TaiKhoanChanging(int value);
    partial void OnID_TaiKhoanChanged();
    partial void OnID_LoaiTaiKhoanChanging(System.Nullable<int> value);
    partial void OnID_LoaiTaiKhoanChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnID_VungChanging(System.Nullable<int> value);
    partial void OnID_VungChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._LoaiTaiKhoan = default(EntityRef<LoaiTaiKhoan>);
			this._VungMien = default(EntityRef<VungMien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TaiKhoan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_TaiKhoan
		{
			get
			{
				return this._ID_TaiKhoan;
			}
			set
			{
				if ((this._ID_TaiKhoan != value))
				{
					this.OnID_TaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._ID_TaiKhoan = value;
					this.SendPropertyChanged("ID_TaiKhoan");
					this.OnID_TaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LoaiTaiKhoan", DbType="Int")]
		public System.Nullable<int> ID_LoaiTaiKhoan
		{
			get
			{
				return this._ID_LoaiTaiKhoan;
			}
			set
			{
				if ((this._ID_LoaiTaiKhoan != value))
				{
					if (this._LoaiTaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_LoaiTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._ID_LoaiTaiKhoan = value;
					this.SendPropertyChanged("ID_LoaiTaiKhoan");
					this.OnID_LoaiTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(150)")]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(250)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(50)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Vung", DbType="Int")]
		public System.Nullable<int> ID_Vung
		{
			get
			{
				return this._ID_Vung;
			}
			set
			{
				if ((this._ID_Vung != value))
				{
					if (this._VungMien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_VungChanging(value);
					this.SendPropertyChanging();
					this._ID_Vung = value;
					this.SendPropertyChanged("ID_Vung");
					this.OnID_VungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiTaiKhoan_TaiKhoan", Storage="_LoaiTaiKhoan", ThisKey="ID_LoaiTaiKhoan", OtherKey="ID_LoaiTaiKhoan", IsForeignKey=true)]
		public LoaiTaiKhoan LoaiTaiKhoan
		{
			get
			{
				return this._LoaiTaiKhoan.Entity;
			}
			set
			{
				LoaiTaiKhoan previousValue = this._LoaiTaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._LoaiTaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiTaiKhoan.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._LoaiTaiKhoan.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._ID_LoaiTaiKhoan = value.ID_LoaiTaiKhoan;
					}
					else
					{
						this._ID_LoaiTaiKhoan = default(Nullable<int>);
					}
					this.SendPropertyChanged("LoaiTaiKhoan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VungMien_TaiKhoan", Storage="_VungMien", ThisKey="ID_Vung", OtherKey="ID_Vung", IsForeignKey=true)]
		public VungMien VungMien
		{
			get
			{
				return this._VungMien.Entity;
			}
			set
			{
				VungMien previousValue = this._VungMien.Entity;
				if (((previousValue != value) 
							|| (this._VungMien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VungMien.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._VungMien.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._ID_Vung = value.ID_Vung;
					}
					else
					{
						this._ID_Vung = default(Nullable<int>);
					}
					this.SendPropertyChanged("VungMien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TinViecLam")]
	public partial class TinViecLam : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_ViecLam;
		
		private string _TieuDeViecLam;
		
		private string _MoTa;
		
		private System.Nullable<int> _ID_NganhNghe;
		
		private System.Nullable<int> _ID_ViTri;
		
		private string _GioiTinh;
		
		private string _YeuCauKyNang;
		
		private string _ThoiGianThuViec;
		
		private System.Nullable<int> _ID_KinhNghiem;
		
		private System.Nullable<int> _ID_TrinhDo;
		
		private string _MucLuong;
		
		private System.Nullable<System.DateTime> _NgayDang;
		
		private System.Nullable<System.DateTime> _NgayHetHan;
		
		private System.Nullable<bool> _TrangThai;
		
		private System.Nullable<int> _ID_CongTy;
		
		private System.Nullable<int> _SoLuong;
		
		private string _YeuCauHoSo;
		
		private EntitySet<DangKy> _DangKies;
		
		private EntityRef<CongTy> _CongTy;
		
		private EntityRef<KinhNghiem> _KinhNghiem;
		
		private EntityRef<NganhNghe> _NganhNghe;
		
		private EntityRef<TrinhDo> _TrinhDo;
		
		private EntityRef<ViTriUngTuyen> _ViTriUngTuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ViecLamChanging(int value);
    partial void OnID_ViecLamChanged();
    partial void OnTieuDeViecLamChanging(string value);
    partial void OnTieuDeViecLamChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnID_NganhNgheChanging(System.Nullable<int> value);
    partial void OnID_NganhNgheChanged();
    partial void OnID_ViTriChanging(System.Nullable<int> value);
    partial void OnID_ViTriChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnYeuCauKyNangChanging(string value);
    partial void OnYeuCauKyNangChanged();
    partial void OnThoiGianThuViecChanging(string value);
    partial void OnThoiGianThuViecChanged();
    partial void OnID_KinhNghiemChanging(System.Nullable<int> value);
    partial void OnID_KinhNghiemChanged();
    partial void OnID_TrinhDoChanging(System.Nullable<int> value);
    partial void OnID_TrinhDoChanged();
    partial void OnMucLuongChanging(string value);
    partial void OnMucLuongChanged();
    partial void OnNgayDangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangChanged();
    partial void OnNgayHetHanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHetHanChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    partial void OnID_CongTyChanging(System.Nullable<int> value);
    partial void OnID_CongTyChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnYeuCauHoSoChanging(string value);
    partial void OnYeuCauHoSoChanged();
    #endregion
		
		public TinViecLam()
		{
			this._DangKies = new EntitySet<DangKy>(new Action<DangKy>(this.attach_DangKies), new Action<DangKy>(this.detach_DangKies));
			this._CongTy = default(EntityRef<CongTy>);
			this._KinhNghiem = default(EntityRef<KinhNghiem>);
			this._NganhNghe = default(EntityRef<NganhNghe>);
			this._TrinhDo = default(EntityRef<TrinhDo>);
			this._ViTriUngTuyen = default(EntityRef<ViTriUngTuyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ViecLam", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_ViecLam
		{
			get
			{
				return this._ID_ViecLam;
			}
			set
			{
				if ((this._ID_ViecLam != value))
				{
					this.OnID_ViecLamChanging(value);
					this.SendPropertyChanging();
					this._ID_ViecLam = value;
					this.SendPropertyChanged("ID_ViecLam");
					this.OnID_ViecLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDeViecLam", DbType="NVarChar(250)")]
		public string TieuDeViecLam
		{
			get
			{
				return this._TieuDeViecLam;
			}
			set
			{
				if ((this._TieuDeViecLam != value))
				{
					this.OnTieuDeViecLamChanging(value);
					this.SendPropertyChanging();
					this._TieuDeViecLam = value;
					this.SendPropertyChanged("TieuDeViecLam");
					this.OnTieuDeViecLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NganhNghe", DbType="Int")]
		public System.Nullable<int> ID_NganhNghe
		{
			get
			{
				return this._ID_NganhNghe;
			}
			set
			{
				if ((this._ID_NganhNghe != value))
				{
					if (this._NganhNghe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_NganhNgheChanging(value);
					this.SendPropertyChanging();
					this._ID_NganhNghe = value;
					this.SendPropertyChanged("ID_NganhNghe");
					this.OnID_NganhNgheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ViTri", DbType="Int")]
		public System.Nullable<int> ID_ViTri
		{
			get
			{
				return this._ID_ViTri;
			}
			set
			{
				if ((this._ID_ViTri != value))
				{
					if (this._ViTriUngTuyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ViTriChanging(value);
					this.SendPropertyChanging();
					this._ID_ViTri = value;
					this.SendPropertyChanged("ID_ViTri");
					this.OnID_ViTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(100)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauKyNang", DbType="NVarChar(MAX)")]
		public string YeuCauKyNang
		{
			get
			{
				return this._YeuCauKyNang;
			}
			set
			{
				if ((this._YeuCauKyNang != value))
				{
					this.OnYeuCauKyNangChanging(value);
					this.SendPropertyChanging();
					this._YeuCauKyNang = value;
					this.SendPropertyChanged("YeuCauKyNang");
					this.OnYeuCauKyNangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianThuViec", DbType="NVarChar(100)")]
		public string ThoiGianThuViec
		{
			get
			{
				return this._ThoiGianThuViec;
			}
			set
			{
				if ((this._ThoiGianThuViec != value))
				{
					this.OnThoiGianThuViecChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianThuViec = value;
					this.SendPropertyChanged("ThoiGianThuViec");
					this.OnThoiGianThuViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_KinhNghiem", DbType="Int")]
		public System.Nullable<int> ID_KinhNghiem
		{
			get
			{
				return this._ID_KinhNghiem;
			}
			set
			{
				if ((this._ID_KinhNghiem != value))
				{
					if (this._KinhNghiem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_KinhNghiemChanging(value);
					this.SendPropertyChanging();
					this._ID_KinhNghiem = value;
					this.SendPropertyChanged("ID_KinhNghiem");
					this.OnID_KinhNghiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TrinhDo", DbType="Int")]
		public System.Nullable<int> ID_TrinhDo
		{
			get
			{
				return this._ID_TrinhDo;
			}
			set
			{
				if ((this._ID_TrinhDo != value))
				{
					if (this._TrinhDo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_TrinhDoChanging(value);
					this.SendPropertyChanging();
					this._ID_TrinhDo = value;
					this.SendPropertyChanged("ID_TrinhDo");
					this.OnID_TrinhDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucLuong", DbType="NVarChar(50)")]
		public string MucLuong
		{
			get
			{
				return this._MucLuong;
			}
			set
			{
				if ((this._MucLuong != value))
				{
					this.OnMucLuongChanging(value);
					this.SendPropertyChanging();
					this._MucLuong = value;
					this.SendPropertyChanged("MucLuong");
					this.OnMucLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this.OnNgayDangChanging(value);
					this.SendPropertyChanging();
					this._NgayDang = value;
					this.SendPropertyChanged("NgayDang");
					this.OnNgayDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHetHan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayHetHan
		{
			get
			{
				return this._NgayHetHan;
			}
			set
			{
				if ((this._NgayHetHan != value))
				{
					this.OnNgayHetHanChanging(value);
					this.SendPropertyChanging();
					this._NgayHetHan = value;
					this.SendPropertyChanged("NgayHetHan");
					this.OnNgayHetHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CongTy", DbType="Int")]
		public System.Nullable<int> ID_CongTy
		{
			get
			{
				return this._ID_CongTy;
			}
			set
			{
				if ((this._ID_CongTy != value))
				{
					if (this._CongTy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_CongTyChanging(value);
					this.SendPropertyChanging();
					this._ID_CongTy = value;
					this.SendPropertyChanged("ID_CongTy");
					this.OnID_CongTyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauHoSo", DbType="NVarChar(MAX)")]
		public string YeuCauHoSo
		{
			get
			{
				return this._YeuCauHoSo;
			}
			set
			{
				if ((this._YeuCauHoSo != value))
				{
					this.OnYeuCauHoSoChanging(value);
					this.SendPropertyChanging();
					this._YeuCauHoSo = value;
					this.SendPropertyChanged("YeuCauHoSo");
					this.OnYeuCauHoSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TinViecLam_DangKy", Storage="_DangKies", ThisKey="ID_ViecLam", OtherKey="ID_ViecLam")]
		public EntitySet<DangKy> DangKies
		{
			get
			{
				return this._DangKies;
			}
			set
			{
				this._DangKies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongTy_TinViecLam", Storage="_CongTy", ThisKey="ID_CongTy", OtherKey="ID_CongTy", IsForeignKey=true)]
		public CongTy CongTy
		{
			get
			{
				return this._CongTy.Entity;
			}
			set
			{
				CongTy previousValue = this._CongTy.Entity;
				if (((previousValue != value) 
							|| (this._CongTy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CongTy.Entity = null;
						previousValue.TinViecLams.Remove(this);
					}
					this._CongTy.Entity = value;
					if ((value != null))
					{
						value.TinViecLams.Add(this);
						this._ID_CongTy = value.ID_CongTy;
					}
					else
					{
						this._ID_CongTy = default(Nullable<int>);
					}
					this.SendPropertyChanged("CongTy");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KinhNghiem_TinViecLam", Storage="_KinhNghiem", ThisKey="ID_KinhNghiem", OtherKey="ID_KinhNghiem", IsForeignKey=true)]
		public KinhNghiem KinhNghiem
		{
			get
			{
				return this._KinhNghiem.Entity;
			}
			set
			{
				KinhNghiem previousValue = this._KinhNghiem.Entity;
				if (((previousValue != value) 
							|| (this._KinhNghiem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KinhNghiem.Entity = null;
						previousValue.TinViecLams.Remove(this);
					}
					this._KinhNghiem.Entity = value;
					if ((value != null))
					{
						value.TinViecLams.Add(this);
						this._ID_KinhNghiem = value.ID_KinhNghiem;
					}
					else
					{
						this._ID_KinhNghiem = default(Nullable<int>);
					}
					this.SendPropertyChanged("KinhNghiem");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NganhNghe_TinViecLam", Storage="_NganhNghe", ThisKey="ID_NganhNghe", OtherKey="ID_NganhNghe", IsForeignKey=true)]
		public NganhNghe NganhNghe
		{
			get
			{
				return this._NganhNghe.Entity;
			}
			set
			{
				NganhNghe previousValue = this._NganhNghe.Entity;
				if (((previousValue != value) 
							|| (this._NganhNghe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NganhNghe.Entity = null;
						previousValue.TinViecLams.Remove(this);
					}
					this._NganhNghe.Entity = value;
					if ((value != null))
					{
						value.TinViecLams.Add(this);
						this._ID_NganhNghe = value.ID_NganhNghe;
					}
					else
					{
						this._ID_NganhNghe = default(Nullable<int>);
					}
					this.SendPropertyChanged("NganhNghe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrinhDo_TinViecLam", Storage="_TrinhDo", ThisKey="ID_TrinhDo", OtherKey="ID_TrinhDo", IsForeignKey=true)]
		public TrinhDo TrinhDo
		{
			get
			{
				return this._TrinhDo.Entity;
			}
			set
			{
				TrinhDo previousValue = this._TrinhDo.Entity;
				if (((previousValue != value) 
							|| (this._TrinhDo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TrinhDo.Entity = null;
						previousValue.TinViecLams.Remove(this);
					}
					this._TrinhDo.Entity = value;
					if ((value != null))
					{
						value.TinViecLams.Add(this);
						this._ID_TrinhDo = value.ID_TrinhDo;
					}
					else
					{
						this._ID_TrinhDo = default(Nullable<int>);
					}
					this.SendPropertyChanged("TrinhDo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ViTriUngTuyen_TinViecLam", Storage="_ViTriUngTuyen", ThisKey="ID_ViTri", OtherKey="ID_ViTri", IsForeignKey=true)]
		public ViTriUngTuyen ViTriUngTuyen
		{
			get
			{
				return this._ViTriUngTuyen.Entity;
			}
			set
			{
				ViTriUngTuyen previousValue = this._ViTriUngTuyen.Entity;
				if (((previousValue != value) 
							|| (this._ViTriUngTuyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ViTriUngTuyen.Entity = null;
						previousValue.TinViecLams.Remove(this);
					}
					this._ViTriUngTuyen.Entity = value;
					if ((value != null))
					{
						value.TinViecLams.Add(this);
						this._ID_ViTri = value.ID_ViTri;
					}
					else
					{
						this._ID_ViTri = default(Nullable<int>);
					}
					this.SendPropertyChanged("ViTriUngTuyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DangKies(DangKy entity)
		{
			this.SendPropertyChanging();
			entity.TinViecLam = this;
		}
		
		private void detach_DangKies(DangKy entity)
		{
			this.SendPropertyChanging();
			entity.TinViecLam = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThanhPho")]
	public partial class ThanhPho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_ThanhPho;
		
		private string _TenThanhPho;
		
		private System.Nullable<int> _ID_Vung;
		
		private EntitySet<CongTy> _CongTies;
		
		private EntitySet<UngVien> _UngViens;
		
		private EntityRef<VungMien> _VungMien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ThanhPhoChanging(int value);
    partial void OnID_ThanhPhoChanged();
    partial void OnTenThanhPhoChanging(string value);
    partial void OnTenThanhPhoChanged();
    partial void OnID_VungChanging(System.Nullable<int> value);
    partial void OnID_VungChanged();
    #endregion
		
		public ThanhPho()
		{
			this._CongTies = new EntitySet<CongTy>(new Action<CongTy>(this.attach_CongTies), new Action<CongTy>(this.detach_CongTies));
			this._UngViens = new EntitySet<UngVien>(new Action<UngVien>(this.attach_UngViens), new Action<UngVien>(this.detach_UngViens));
			this._VungMien = default(EntityRef<VungMien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ThanhPho", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_ThanhPho
		{
			get
			{
				return this._ID_ThanhPho;
			}
			set
			{
				if ((this._ID_ThanhPho != value))
				{
					this.OnID_ThanhPhoChanging(value);
					this.SendPropertyChanging();
					this._ID_ThanhPho = value;
					this.SendPropertyChanged("ID_ThanhPho");
					this.OnID_ThanhPhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThanhPho", DbType="NVarChar(50)")]
		public string TenThanhPho
		{
			get
			{
				return this._TenThanhPho;
			}
			set
			{
				if ((this._TenThanhPho != value))
				{
					this.OnTenThanhPhoChanging(value);
					this.SendPropertyChanging();
					this._TenThanhPho = value;
					this.SendPropertyChanged("TenThanhPho");
					this.OnTenThanhPhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Vung", DbType="Int")]
		public System.Nullable<int> ID_Vung
		{
			get
			{
				return this._ID_Vung;
			}
			set
			{
				if ((this._ID_Vung != value))
				{
					if (this._VungMien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_VungChanging(value);
					this.SendPropertyChanging();
					this._ID_Vung = value;
					this.SendPropertyChanged("ID_Vung");
					this.OnID_VungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhPho_CongTy", Storage="_CongTies", ThisKey="ID_ThanhPho", OtherKey="ID_ThanhPho")]
		public EntitySet<CongTy> CongTies
		{
			get
			{
				return this._CongTies;
			}
			set
			{
				this._CongTies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhPho_UngVien", Storage="_UngViens", ThisKey="ID_ThanhPho", OtherKey="ID_ThanhPho")]
		public EntitySet<UngVien> UngViens
		{
			get
			{
				return this._UngViens;
			}
			set
			{
				this._UngViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VungMien_ThanhPho", Storage="_VungMien", ThisKey="ID_Vung", OtherKey="ID_Vung", IsForeignKey=true)]
		public VungMien VungMien
		{
			get
			{
				return this._VungMien.Entity;
			}
			set
			{
				VungMien previousValue = this._VungMien.Entity;
				if (((previousValue != value) 
							|| (this._VungMien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VungMien.Entity = null;
						previousValue.ThanhPhos.Remove(this);
					}
					this._VungMien.Entity = value;
					if ((value != null))
					{
						value.ThanhPhos.Add(this);
						this._ID_Vung = value.ID_Vung;
					}
					else
					{
						this._ID_Vung = default(Nullable<int>);
					}
					this.SendPropertyChanged("VungMien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CongTies(CongTy entity)
		{
			this.SendPropertyChanging();
			entity.ThanhPho = this;
		}
		
		private void detach_CongTies(CongTy entity)
		{
			this.SendPropertyChanging();
			entity.ThanhPho = null;
		}
		
		private void attach_UngViens(UngVien entity)
		{
			this.SendPropertyChanging();
			entity.ThanhPho = this;
		}
		
		private void detach_UngViens(UngVien entity)
		{
			this.SendPropertyChanging();
			entity.ThanhPho = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TrinhDo")]
	public partial class TrinhDo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_TrinhDo;
		
		private string _TenTrinhDo;
		
		private EntitySet<CV_UngVien> _CV_UngViens;
		
		private EntitySet<TinViecLam> _TinViecLams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_TrinhDoChanging(int value);
    partial void OnID_TrinhDoChanged();
    partial void OnTenTrinhDoChanging(string value);
    partial void OnTenTrinhDoChanged();
    #endregion
		
		public TrinhDo()
		{
			this._CV_UngViens = new EntitySet<CV_UngVien>(new Action<CV_UngVien>(this.attach_CV_UngViens), new Action<CV_UngVien>(this.detach_CV_UngViens));
			this._TinViecLams = new EntitySet<TinViecLam>(new Action<TinViecLam>(this.attach_TinViecLams), new Action<TinViecLam>(this.detach_TinViecLams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TrinhDo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_TrinhDo
		{
			get
			{
				return this._ID_TrinhDo;
			}
			set
			{
				if ((this._ID_TrinhDo != value))
				{
					this.OnID_TrinhDoChanging(value);
					this.SendPropertyChanging();
					this._ID_TrinhDo = value;
					this.SendPropertyChanged("ID_TrinhDo");
					this.OnID_TrinhDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTrinhDo", DbType="NVarChar(250)")]
		public string TenTrinhDo
		{
			get
			{
				return this._TenTrinhDo;
			}
			set
			{
				if ((this._TenTrinhDo != value))
				{
					this.OnTenTrinhDoChanging(value);
					this.SendPropertyChanging();
					this._TenTrinhDo = value;
					this.SendPropertyChanged("TenTrinhDo");
					this.OnTenTrinhDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrinhDo_CV_UngVien", Storage="_CV_UngViens", ThisKey="ID_TrinhDo", OtherKey="ID_TrinhDo")]
		public EntitySet<CV_UngVien> CV_UngViens
		{
			get
			{
				return this._CV_UngViens;
			}
			set
			{
				this._CV_UngViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrinhDo_TinViecLam", Storage="_TinViecLams", ThisKey="ID_TrinhDo", OtherKey="ID_TrinhDo")]
		public EntitySet<TinViecLam> TinViecLams
		{
			get
			{
				return this._TinViecLams;
			}
			set
			{
				this._TinViecLams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CV_UngViens(CV_UngVien entity)
		{
			this.SendPropertyChanging();
			entity.TrinhDo = this;
		}
		
		private void detach_CV_UngViens(CV_UngVien entity)
		{
			this.SendPropertyChanging();
			entity.TrinhDo = null;
		}
		
		private void attach_TinViecLams(TinViecLam entity)
		{
			this.SendPropertyChanging();
			entity.TrinhDo = this;
		}
		
		private void detach_TinViecLams(TinViecLam entity)
		{
			this.SendPropertyChanging();
			entity.TrinhDo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UngVien")]
	public partial class UngVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_UngVien;
		
		private string _HoTen;
		
		private string _MatKhau;
		
		private string _DiaChi;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _GioiTinh;
		
		private string _Email;
		
		private string _SDT;
		
		private System.Nullable<int> _ID_ThanhPho;
		
		private EntitySet<CV_UngVien> _CV_UngViens;
		
		private EntityRef<ThanhPho> _ThanhPho;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_UngVienChanging(int value);
    partial void OnID_UngVienChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnID_ThanhPhoChanging(System.Nullable<int> value);
    partial void OnID_ThanhPhoChanged();
    #endregion
		
		public UngVien()
		{
			this._CV_UngViens = new EntitySet<CV_UngVien>(new Action<CV_UngVien>(this.attach_CV_UngViens), new Action<CV_UngVien>(this.detach_CV_UngViens));
			this._ThanhPho = default(EntityRef<ThanhPho>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_UngVien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_UngVien
		{
			get
			{
				return this._ID_UngVien;
			}
			set
			{
				if ((this._ID_UngVien != value))
				{
					this.OnID_UngVienChanging(value);
					this.SendPropertyChanging();
					this._ID_UngVien = value;
					this.SendPropertyChanged("ID_UngVien");
					this.OnID_UngVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(150)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(100)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(250)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(50)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(50)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ThanhPho", DbType="Int")]
		public System.Nullable<int> ID_ThanhPho
		{
			get
			{
				return this._ID_ThanhPho;
			}
			set
			{
				if ((this._ID_ThanhPho != value))
				{
					if (this._ThanhPho.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ThanhPhoChanging(value);
					this.SendPropertyChanging();
					this._ID_ThanhPho = value;
					this.SendPropertyChanged("ID_ThanhPho");
					this.OnID_ThanhPhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UngVien_CV_UngVien", Storage="_CV_UngViens", ThisKey="ID_UngVien", OtherKey="ID_UngVien")]
		public EntitySet<CV_UngVien> CV_UngViens
		{
			get
			{
				return this._CV_UngViens;
			}
			set
			{
				this._CV_UngViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhPho_UngVien", Storage="_ThanhPho", ThisKey="ID_ThanhPho", OtherKey="ID_ThanhPho", IsForeignKey=true)]
		public ThanhPho ThanhPho
		{
			get
			{
				return this._ThanhPho.Entity;
			}
			set
			{
				ThanhPho previousValue = this._ThanhPho.Entity;
				if (((previousValue != value) 
							|| (this._ThanhPho.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThanhPho.Entity = null;
						previousValue.UngViens.Remove(this);
					}
					this._ThanhPho.Entity = value;
					if ((value != null))
					{
						value.UngViens.Add(this);
						this._ID_ThanhPho = value.ID_ThanhPho;
					}
					else
					{
						this._ID_ThanhPho = default(Nullable<int>);
					}
					this.SendPropertyChanged("ThanhPho");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CV_UngViens(CV_UngVien entity)
		{
			this.SendPropertyChanging();
			entity.UngVien = this;
		}
		
		private void detach_CV_UngViens(CV_UngVien entity)
		{
			this.SendPropertyChanging();
			entity.UngVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViTriUngTuyen")]
	public partial class ViTriUngTuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_ViTri;
		
		private string _TenViTri;
		
		private EntitySet<CV_UngVien> _CV_UngViens;
		
		private EntitySet<TinViecLam> _TinViecLams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ViTriChanging(int value);
    partial void OnID_ViTriChanged();
    partial void OnTenViTriChanging(string value);
    partial void OnTenViTriChanged();
    #endregion
		
		public ViTriUngTuyen()
		{
			this._CV_UngViens = new EntitySet<CV_UngVien>(new Action<CV_UngVien>(this.attach_CV_UngViens), new Action<CV_UngVien>(this.detach_CV_UngViens));
			this._TinViecLams = new EntitySet<TinViecLam>(new Action<TinViecLam>(this.attach_TinViecLams), new Action<TinViecLam>(this.detach_TinViecLams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ViTri", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_ViTri
		{
			get
			{
				return this._ID_ViTri;
			}
			set
			{
				if ((this._ID_ViTri != value))
				{
					this.OnID_ViTriChanging(value);
					this.SendPropertyChanging();
					this._ID_ViTri = value;
					this.SendPropertyChanged("ID_ViTri");
					this.OnID_ViTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenViTri", DbType="NVarChar(255)")]
		public string TenViTri
		{
			get
			{
				return this._TenViTri;
			}
			set
			{
				if ((this._TenViTri != value))
				{
					this.OnTenViTriChanging(value);
					this.SendPropertyChanging();
					this._TenViTri = value;
					this.SendPropertyChanged("TenViTri");
					this.OnTenViTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ViTriUngTuyen_CV_UngVien", Storage="_CV_UngViens", ThisKey="ID_ViTri", OtherKey="ID_ViTri")]
		public EntitySet<CV_UngVien> CV_UngViens
		{
			get
			{
				return this._CV_UngViens;
			}
			set
			{
				this._CV_UngViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ViTriUngTuyen_TinViecLam", Storage="_TinViecLams", ThisKey="ID_ViTri", OtherKey="ID_ViTri")]
		public EntitySet<TinViecLam> TinViecLams
		{
			get
			{
				return this._TinViecLams;
			}
			set
			{
				this._TinViecLams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CV_UngViens(CV_UngVien entity)
		{
			this.SendPropertyChanging();
			entity.ViTriUngTuyen = this;
		}
		
		private void detach_CV_UngViens(CV_UngVien entity)
		{
			this.SendPropertyChanging();
			entity.ViTriUngTuyen = null;
		}
		
		private void attach_TinViecLams(TinViecLam entity)
		{
			this.SendPropertyChanging();
			entity.ViTriUngTuyen = this;
		}
		
		private void detach_TinViecLams(TinViecLam entity)
		{
			this.SendPropertyChanging();
			entity.ViTriUngTuyen = null;
		}
	}
}
#pragma warning restore 1591
